# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
      args: ['--maxkb=500'] # set the max file size to 500KB

# - repo: https://github.com/psf/black
#   rev: 25.1.0  # Use the latest stable version
#   hooks:
#     - id: black

# - repo: https://github.com/PyCQA/flake8
#   rev: 7.1.1  # Use the latest stable version
#   hooks:
#     - id: flake8

# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: 6.0.0  # Use the latest stable version
#   hooks:
#     - id: isort
