[tox]
envlist = py310,py311,py312,py313

[testenv]
deps = 
    matplotlib
    numba
    numpy
    pandas
    scipy
    joblib
    pandera
    tdqm
commands = python -m unittest discover -s tests

[testenv:py310]
basepython = python3.10

[testenv:py311]
basepython = python3.11

[testenv:py312]
basepython = python3.12

[testenv:py313]
basepython = python3.13