name: CI

on:
  push:
    branches:
      - main
      - dev
      - tests_ci
  pull_request:
    branches:
      - main
      - dev
      - tests_ci

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: myenv
          environment-file: environment.yml
          # condarc-file: etc/example-condarc.yml
          auto-activate-base: false
      - run: |
          # conda info
          # conda list
          # conda install -c conda-forge llvmdev=14.0.6  # Install LLVM
          # conda install -c conda-forge rust  # Install Rust for building pydantic-cor   
          python -m pip install --upgrade pip
          pip install setuptools --upgrade
          pip install ./
                
      - name: Run tests
        run: |    
          python -m unittest discover -s tests

# jobs:
#   # build-venv:
#   #   runs-on: ubuntu-latest

#   #   steps:
#   #   - name: Checkout code
#   #     uses: actions/checkout@v3

#   #   - name: Set up Python
#   #     uses: actions/setup-python@v4
#   #     with:
#   #       python-version: '3.10'

#   #   - name: Set up environment
#   #     run: |
#   #       python -m venv venv
#   #       source venv/bin/activate

#   #   - name: Install dependencies
#   #     run: |
#   #       source venv/bin/activate
#   #       python -m pip install --upgrade pip
#   #       pip install ./

#   #   - name: Run tests
#   #     run: |
#   #       source venv/bin/activate
#   #       python -m unittest discover -s tests

#   build-conda:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Conda
#       uses: conda-incubator/setup-miniconda@v2
#       with:
#         python-version: '3.10'
#         miniconda-version: 'latest'
#         channels: 'conda-forge'
#         auto-activate-base: false
#         environment-file: environment.yml
#         activate-environment: myenv

#     - name: Create Conda environment
#       shell: bash -l {0}
#       run: |
#         $CONDA/bin/conda create --name myenv python=3.10 -y
#         $CONDA/bin/conda activate myenv

# #     - name: Install dependencies
# #       run: |
# #         $CONDA/bin/conda init
# #         $CONDA/bin/conda activate myenv
# #        python -m pip install --upgrade pip
# #        pip install ./

# #     - name: Run tests
# #       run: |
# #         source ~/.bashrc
# #         conda activate myenv
# #         python -m unittest discover -s tests
