name: CI

on:
  push:
    branches:
      - main
      - dev
      - tests_ci
  pull_request:
    branches:
      - main
      - dev
      - tests_ci

jobs:
  build-venv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install ./

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s tests

  build-conda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'

    - name: Create Conda environment
      run: |
        conda create --name myenv python=3.10 -y

    - name: Install dependencies
      run: |
        conda init
        conda activate myenv
        python -m pip install --upgrade pip
        pip install ./

    - name: Run tests
      run: |
        python -m unittest discover -s tests
